version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: gval-build
    main: ./...
    ldflags:
      - -s -w -X main.version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
    ignore:
      - goos: darwin
        goarch: amd64
      - goos: windows
        goarch: arm64
      - goos: linux
        goarch: arm64

archives:
  - id: gval-archives
  - formats: [tar.gz]
    name_template: '{{ .ProjectName }}-{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md

nfpms:
  - description: CLI validator utilizing go-playground/validator
    homepage: https://github.com/mrccnt/gval/
    id: gval-nfpms
    package_name: gval
    file_name_template: "{{ .ProjectName }}-{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    maintainer: "Marco Conti <github@marcoconti.org>"
    license: Apache-2.0
    section: golang
    formats:
      - deb
      - rpm
    umask: 0o022
    rpm:
      group: Development/Tools
    overrides:
      deb:
        contents:
          - src: LICENSE
            dst: /usr/share/doc/gval/LICENSE
          - src: README.md
            dst: /usr/share/doc/gval/README.md
      rpm:
        contents:
          - src: LICENSE
            dst: /usr/share/doc/gval/LICENSE
            type: license
          - src: README.md
            dst: /usr/share/doc/gval/README.md
            type: readme

dockers_v2:
  - id: gval-alpine
    images:
      - 'marcocontiorg/gval'
    dockerfile: Dockerfile
    platforms:
      - linux/amd64
    tags:
      - "{{ .Version }}"
      - "{{ if .IsNightly }}nightly{{ end }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    labels:
      'org.opencontainers.image.title': '{{.ProjectName}}'
      'org.opencontainers.image.description': 'CLI validator utilizing go-playground/validator'
      'org.opencontainers.image.source': '{{.GitURL}}'
      'org.opencontainers.image.url': '{{.GitURL}}'
      'org.opencontainers.image.documentation': 'https://github.com/mrccnt/gval'
      'org.opencontainers.image.created': '{{.Date}}'
      'org.opencontainers.image.revision': '{{.FullCommit}}'
      'org.opencontainers.image.version': '{{.Version}}'
      'org.opencontainers.image.base.name': '{{.BaseImage}}'
      'org.opencontainers.image.base.digest': '{{.BaseImageDigest}}'
      'index,manifest:org.opencontainers.image.licenses': 'Apache-2.0'
    disable: "{{ .IsSnapshot }}"

sboms:
  - id: gval-sboms-archive
    documents:
      - "${artifact}.spdx.json"
    cmd: syft
    args: ["$artifact", "--output", "cyclonedx-json=$document"]
    artifacts: archive
  - id: gval-sboms-package
    documents:
      - "${artifact}.spdx.json"
    cmd: syft
    args: ["$artifact", "--output", "cyclonedx-json=$document"]
    artifacts: package

checksum:
  name_template: "checksums.sha256"
  algorithm: sha256

release:
  github:
    owner: mrccnt
    name: gval
  skip_upload: "{{ .IsSnapshot }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '(?i)^docs?:'
      - '(?i)^test?:'
      - Merge pull request
      - Merge branch
